
services:
  usdc-tracker:
    build: .
    container_name: usdc-tracker
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - usdcnet
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - usdc-tracker
    networks:
      - usdcnet
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: rustuser
      POSTGRES_PASSWORD: rustpass
      POSTGRES_DB: rustdb
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - usdcnet

networks:
  usdcnet:
    driver: bridge

volumes:
  db_data:
