[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.21"
db = { path = "../db" }
anyhow = "1.0"
