[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde = { version = "1.0", features = ["derive"] }
db = { path = "../db" }
chrono = "0.4.42"
serde_json = "1.0.145"
